<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/scope.php';
$hospitalAdmin = requireHospitalAdmin();
$hospitalPageTitle = 'Hospital Bookings';
$connection = getMySqlConnection();
$statement = $connection->prepare('SELECT a.id, a.appointment_reference, a.patient_name, a.contact_number, a.email, a.emergency_contact_name, a.emergency_contact_number, a.dialysis_type, a.appointment_date, a.appointment_time, a.created_at, a.status, a.rejection_reason, a.notes FROM appointments a WHERE a.hospital_id = :hospital_id ORDER BY a.appointment_date DESC, a.appointment_time DESC');
$statement->execute(['hospital_id' => currentHospitalId()]);
$bookings = $statement->fetchAll();
require __DIR__ . '/includes/header.php';
?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Booking ID</th><th>Patient</th><th>Contact</th><th>Dialysis Type</th><th>Date</th><th>Time</th><th>Booking Date</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($bookings as $booking): ?><tr><td><?= htmlspecialchars($booking['appointment_reference'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['patient_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['contact_number'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['dialysis_type'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['appointment_date'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['appointment_time'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['created_at'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['status'], ENT_QUOTES, 'UTF-8') ?><?php if ($booking['rejection_reason']): ?><br><small><?= htmlspecialchars($booking['rejection_reason'], ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></td><td><div class="booking-action-panel"><div class="booking-action-header">Actions</div><details><summary>View</summary><p>Email: <?= htmlspecialchars($booking['email'], ENT_QUOTES, 'UTF-8') ?></p><p>Emergency: <?= htmlspecialchars($booking['emergency_contact_name'], ENT_QUOTES, 'UTF-8') ?> (<?= htmlspecialchars($booking['emergency_contact_number'], ENT_QUOTES, 'UTF-8') ?>)</p><p>Notes: <?= htmlspecialchars($booking['notes'] ?? '', ENT_QUOTES, 'UTF-8') ?></p></details><?php if (in_array($booking['status'], ['Pending Confirmation', 'Confirmed'], true)): ?><form class="booking-action-form" method="post" action="actions/update_booking.php"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(getCsrfToken(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="appointment_id" value="<?= (int) $booking['id'] ?>"><select name="status" required><option value="Confirmed">Confirm</option><option value="Rejected">Reject</option><option value="Completed">Complete</option><option value="Cancelled">Cancel</option></select><input name="rejection_reason" maxlength="500" placeholder="Reason if rejecting"><button class="admin-btn" type="submit">Save</button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table><?php if (!$bookings): ?><p class="admin-empty">No bookings for this hospital.</p><?php endif; ?></div><?php require __DIR__ . '/includes/footer.php'; ?>