<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/auth.php'; require_once __DIR__ . '/includes/db.php';
$adminUser = requireAdmin(); $adminPageTitle = 'Bookings';
$status = requestEnum($_GET, 'status', ['Pending Confirmation','Confirmed','Completed','Cancelled']);
$sql = 'SELECT a.*, u.name AS user_name FROM appointments a LEFT JOIN users u ON u.id = a.user_id'; $params = [];
if ($status !== '') { $sql .= ' WHERE a.status = :status'; $params['status'] = $status; } $sql .= ' ORDER BY a.appointment_date DESC, a.appointment_time DESC';
$statement = $adminConnection->prepare($sql); $statement->execute($params); $bookings = $statement->fetchAll();
require __DIR__ . '/includes/header.php';
?><div class="admin-toolbar"><form class="admin-toolbar" method="get"><label class="admin-field">Status<select name="status"><option value="">All statuses</option><?php foreach (['Pending Confirmation','Confirmed','Completed','Cancelled'] as $option): ?><option <?= $status === $option ? 'selected' : '' ?>><?= htmlspecialchars($option, ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label><button class="admin-btn admin-btn-secondary" type="submit">Filter</button></form></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Reference</th><th>Patient</th><th>Center</th><th>Date / Time</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach ($bookings as $booking): ?><tr><td><?= htmlspecialchars($booking['appointment_reference'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['user_name'] ?? $booking['patient_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['center_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['appointment_date'], ENT_QUOTES, 'UTF-8') ?><br><?= htmlspecialchars(substr($booking['appointment_time'], 0, 5), ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($booking['dialysis_type'], ENT_QUOTES, 'UTF-8') ?></td><td><span class="admin-status"><?= htmlspecialchars($booking['status'], ENT_QUOTES, 'UTF-8') ?></span></td><td><form method="post" action="actions/update_booking.php"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(getCsrfToken(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="appointment_id" value="<?= (int) $booking['id'] ?>"><select name="status"><option>Pending Confirmation</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select><button class="admin-btn" type="submit">Update</button></form></td></tr><?php endforeach; ?></tbody></table><?php if (!$bookings): ?><p class="admin-empty">No bookings match this filter.</p><?php endif; ?></div><?php require __DIR__ . '/includes/footer.php'; ?>
